# The Docker image that will be used to build your app
image: nodejs
# Functions that should be executed before the build script is run
before_script:
  - npm ci
pages:
  cache: #
    paths:
      - node_modules/
  script:
    - npm install -g @angular/cli@10.0.0 #
    - npm install
    - ng build --configuration=production #
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
